BB import
henriquebastos/pds-api-client pull request #1
Opened 2022-02-04 00:14 UTC by henriquebastos

2022-02-04 00:15 UTC, kneipp requested changes

2022-02-04 00:15 UTC, kneipp commented on bbapilib/__init__.py
> +import requests
test

2022-02-04 00:17 UTC, lays147 commented on bbapilib/__init__.py
> +import requests
requests não está deprecado, daria pra trocar por httpx?

2022-02-04 00:17 UTC, lays147 commented on bbapilib/__init__.py
> +    def basic_auth_gen(self, client_id, client_secret):
poderia ser static method por não usar o `self`.

2022-02-04 00:17 UTC, lays147 commented on bbapilib/__init__.py
> +        pprint(f"Basic AUTH: {resp}")
usar `logging` em vez de `pprint`

2022-02-07 16:08 UTC, tiagosamaha commented on bbapilib/__init__.py
> +        params_str = "&".join(params_str)
Pode utilizar `urllib.urlencode`.

2022-02-07 16:24 UTC, tiagosamaha commented on bbapilib/__init__.py
> +        if 200 != rspnc.status_code:
Pode utilizar o `HTTPStatus` do módulo `http` para deixar mais verboso.

`HTTPStatus.OK  != rspnc.status_code`

2022-02-08 01:31 UTC, andredelorme commented on bbapilib/__init__.py
> +import requests
Não diria deprecado, mas uma alternativa, possivelmente mais moderna.
Não conhecia, valeu a dica.

2022-02-08 01:32 UTC, andredelorme commented on bbapilib/__init__.py
> +        self.basic_auth = self.basic_auth_gen(client_id, client_secret)
Para Basic Authentication, basta usar o parâmetro auth com uma tupla com user e pass

2022-02-08 01:35 UTC, andredelorme commented on bbapilib/__init__.py
> +        rspnc = requests.get(url_param, headers=self.header, **kwargs)
Por que não usar o parâmetro params ao invés de montar a URL com a querystring manualmente?

2022-02-08 01:39 UTC, andredelorme commented on bbapilib/__init__.py
> +        data = {
O problema da paginação não seria a estrutura? Algo como:
```
data = {
    'inicio': dthr_ini,
    'fim': "2021-12-24T23:59:59Z",
    'paginacao': {
        'paginaAtual': 1,
        'itensPorPagina': 50,
        'quantidadeDePaginas': 4,
        'quantidadeTotalDeItens': 167,
    }
}
```

2022-06-09 12:15 UTC, merged